#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libxml2-legacy
Version  : 2.9.7
Release  : 1
URL      : https://git.gnome.org/browse/libxml2/snapshot/libxml2-2.9.7.tar.xz
Source0  : https://git.gnome.org/browse/libxml2/snapshot/libxml2-2.9.7.tar.xz
Summary  : libXML library version2.
Group    : Development/Tools
License  : MIT
Requires: libxml2-legacy-bin
Requires: libxml2-legacy-lib
Requires: libxml2-legacy-data
Requires: libxml2-legacy-doc
BuildRequires : pkgconfig(icu-i18n)
BuildRequires : pkgconfig(liblzma)
BuildRequires : pkgconfig(zlib)
BuildRequires : python3-dev

%description
XML toolkit from the GNOME project
Full documentation is available on-line at
http://xmlsoft.org/

%package bin
Summary: bin components for the libxml2-legacy package.
Group: Binaries
Requires: libxml2-legacy-data

%description bin
bin components for the libxml2-legacy package.


%package data
Summary: data components for the libxml2-legacy package.
Group: Data

%description data
data components for the libxml2-legacy package.


%package dev
Summary: dev components for the libxml2-legacy package.
Group: Development
Requires: libxml2-legacy-lib
Requires: libxml2-legacy-bin
Requires: libxml2-legacy-data
Provides: libxml2-legacy-devel

%description dev
dev components for the libxml2-legacy package.


%package doc
Summary: doc components for the libxml2-legacy package.
Group: Documentation

%description doc
doc components for the libxml2-legacy package.


%package lib
Summary: lib components for the libxml2-legacy package.
Group: Libraries
Requires: libxml2-legacy-data

%description lib
lib components for the libxml2-legacy package.


%prep
%setup -q -n libxml2-2.9.7

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1517707329
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong "
%autogen --disable-static PYTHON=/usr/bin/python2
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1517707329
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
/usr/lib64/cmake/libxml2/libxml2-config.cmake
/usr/lib64/xml2Conf.sh

%files bin
%defattr(-,root,root,-)
/usr/bin/xml2-config
/usr/bin/xmlcatalog
/usr/bin/xmllint

%files data
%defattr(-,root,root,-)
/usr/share/doc/libxml2-2.9.7/Copyright
/usr/share/doc/libxml2-2.9.7/examples/testHTML.c
/usr/share/doc/libxml2-2.9.7/examples/testSAX.c
/usr/share/doc/libxml2-2.9.7/examples/testXPath.c
/usr/share/doc/libxml2-2.9.7/examples/xmllint.c
/usr/share/doc/libxml2-2.9.7/html/DOM.gif
/usr/share/doc/libxml2-2.9.7/html/FAQ.html
/usr/share/doc/libxml2-2.9.7/html/Libxml2-Logo-180x168.gif
/usr/share/doc/libxml2-2.9.7/html/Libxml2-Logo-90x34.gif
/usr/share/doc/libxml2-2.9.7/html/encoding.html
/usr/share/doc/libxml2-2.9.7/html/examples.xml
/usr/share/doc/libxml2-2.9.7/html/examples.xsl
/usr/share/doc/libxml2-2.9.7/html/html/book1.html
/usr/share/doc/libxml2-2.9.7/html/html/home.png
/usr/share/doc/libxml2-2.9.7/html/html/index.html
/usr/share/doc/libxml2-2.9.7/html/html/left.png
/usr/share/doc/libxml2-2.9.7/html/html/libxml-DOCBparser.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-HTMLparser.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-HTMLtree.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-SAX.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-SAX2.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-c14n.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-catalog.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-chvalid.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-debugXML.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-dict.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-encoding.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-entities.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-globals.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-hash.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-lib.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-list.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-nanoftp.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-nanohttp.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-parser.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-parserInternals.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-pattern.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-relaxng.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-schemasInternals.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-schematron.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-threads.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-tree.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-uri.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-valid.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-xinclude.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-xlink.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-xmlIO.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-xmlautomata.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-xmlerror.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-xmlexports.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-xmlmemory.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-xmlmodule.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-xmlreader.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-xmlregexp.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-xmlsave.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-xmlschemas.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-xmlschemastypes.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-xmlstring.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-xmlunicode.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-xmlversion.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-xmlwriter.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-xpath.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-xpathInternals.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-xpointer.html
/usr/share/doc/libxml2-2.9.7/html/html/libxml-xzlib.html
/usr/share/doc/libxml2-2.9.7/html/html/right.png
/usr/share/doc/libxml2-2.9.7/html/html/up.png
/usr/share/doc/libxml2-2.9.7/html/index.html
/usr/share/doc/libxml2-2.9.7/html/io1.c
/usr/share/doc/libxml2-2.9.7/html/io1.res
/usr/share/doc/libxml2-2.9.7/html/io2.c
/usr/share/doc/libxml2-2.9.7/html/io2.res
/usr/share/doc/libxml2-2.9.7/html/libxml.gif
/usr/share/doc/libxml2-2.9.7/html/parse1.c
/usr/share/doc/libxml2-2.9.7/html/parse2.c
/usr/share/doc/libxml2-2.9.7/html/parse3.c
/usr/share/doc/libxml2-2.9.7/html/parse4.c
/usr/share/doc/libxml2-2.9.7/html/reader1.c
/usr/share/doc/libxml2-2.9.7/html/reader1.res
/usr/share/doc/libxml2-2.9.7/html/reader2.c
/usr/share/doc/libxml2-2.9.7/html/reader3.c
/usr/share/doc/libxml2-2.9.7/html/reader3.res
/usr/share/doc/libxml2-2.9.7/html/reader4.c
/usr/share/doc/libxml2-2.9.7/html/reader4.res
/usr/share/doc/libxml2-2.9.7/html/redhat.gif
/usr/share/doc/libxml2-2.9.7/html/smallfootonly.gif
/usr/share/doc/libxml2-2.9.7/html/structure.gif
/usr/share/doc/libxml2-2.9.7/html/test1.xml
/usr/share/doc/libxml2-2.9.7/html/test2.xml
/usr/share/doc/libxml2-2.9.7/html/test3.xml
/usr/share/doc/libxml2-2.9.7/html/testWriter.c
/usr/share/doc/libxml2-2.9.7/html/tree1.c
/usr/share/doc/libxml2-2.9.7/html/tree1.res
/usr/share/doc/libxml2-2.9.7/html/tree2.c
/usr/share/doc/libxml2-2.9.7/html/tree2.res
/usr/share/doc/libxml2-2.9.7/html/tst.xml
/usr/share/doc/libxml2-2.9.7/html/tutorial/apa.html
/usr/share/doc/libxml2-2.9.7/html/tutorial/apb.html
/usr/share/doc/libxml2-2.9.7/html/tutorial/apc.html
/usr/share/doc/libxml2-2.9.7/html/tutorial/apd.html
/usr/share/doc/libxml2-2.9.7/html/tutorial/ape.html
/usr/share/doc/libxml2-2.9.7/html/tutorial/apf.html
/usr/share/doc/libxml2-2.9.7/html/tutorial/apg.html
/usr/share/doc/libxml2-2.9.7/html/tutorial/aph.html
/usr/share/doc/libxml2-2.9.7/html/tutorial/api.html
/usr/share/doc/libxml2-2.9.7/html/tutorial/ar01s02.html
/usr/share/doc/libxml2-2.9.7/html/tutorial/ar01s03.html
/usr/share/doc/libxml2-2.9.7/html/tutorial/ar01s04.html
/usr/share/doc/libxml2-2.9.7/html/tutorial/ar01s05.html
/usr/share/doc/libxml2-2.9.7/html/tutorial/ar01s06.html
/usr/share/doc/libxml2-2.9.7/html/tutorial/ar01s07.html
/usr/share/doc/libxml2-2.9.7/html/tutorial/ar01s08.html
/usr/share/doc/libxml2-2.9.7/html/tutorial/ar01s09.html
/usr/share/doc/libxml2-2.9.7/html/tutorial/customfo.xsl
/usr/share/doc/libxml2-2.9.7/html/tutorial/customhtml.xsl
/usr/share/doc/libxml2-2.9.7/html/tutorial/images/blank.png
/usr/share/doc/libxml2-2.9.7/html/tutorial/images/callouts/1.png
/usr/share/doc/libxml2-2.9.7/html/tutorial/images/callouts/10.png
/usr/share/doc/libxml2-2.9.7/html/tutorial/images/callouts/2.png
/usr/share/doc/libxml2-2.9.7/html/tutorial/images/callouts/3.png
/usr/share/doc/libxml2-2.9.7/html/tutorial/images/callouts/4.png
/usr/share/doc/libxml2-2.9.7/html/tutorial/images/callouts/5.png
/usr/share/doc/libxml2-2.9.7/html/tutorial/images/callouts/6.png
/usr/share/doc/libxml2-2.9.7/html/tutorial/images/callouts/7.png
/usr/share/doc/libxml2-2.9.7/html/tutorial/images/callouts/8.png
/usr/share/doc/libxml2-2.9.7/html/tutorial/images/callouts/9.png
/usr/share/doc/libxml2-2.9.7/html/tutorial/images/caution.png
/usr/share/doc/libxml2-2.9.7/html/tutorial/images/draft.png
/usr/share/doc/libxml2-2.9.7/html/tutorial/images/home.png
/usr/share/doc/libxml2-2.9.7/html/tutorial/images/important.png
/usr/share/doc/libxml2-2.9.7/html/tutorial/images/next.png
/usr/share/doc/libxml2-2.9.7/html/tutorial/images/note.png
/usr/share/doc/libxml2-2.9.7/html/tutorial/images/prev.png
/usr/share/doc/libxml2-2.9.7/html/tutorial/images/tip.png
/usr/share/doc/libxml2-2.9.7/html/tutorial/images/toc-blank.png
/usr/share/doc/libxml2-2.9.7/html/tutorial/images/toc-minus.png
/usr/share/doc/libxml2-2.9.7/html/tutorial/images/toc-plus.png
/usr/share/doc/libxml2-2.9.7/html/tutorial/images/up.png
/usr/share/doc/libxml2-2.9.7/html/tutorial/images/warning.png
/usr/share/doc/libxml2-2.9.7/html/tutorial/includeaddattribute.c
/usr/share/doc/libxml2-2.9.7/html/tutorial/includeaddkeyword.c
/usr/share/doc/libxml2-2.9.7/html/tutorial/includeconvert.c
/usr/share/doc/libxml2-2.9.7/html/tutorial/includegetattribute.c
/usr/share/doc/libxml2-2.9.7/html/tutorial/includekeyword.c
/usr/share/doc/libxml2-2.9.7/html/tutorial/includestory.xml
/usr/share/doc/libxml2-2.9.7/html/tutorial/includexpath.c
/usr/share/doc/libxml2-2.9.7/html/tutorial/index.html
/usr/share/doc/libxml2-2.9.7/html/tutorial/ix01.html
/usr/share/doc/libxml2-2.9.7/html/tutorial/xmltutorial.pdf
/usr/share/doc/libxml2-2.9.7/html/tutorial/xmltutorial.xml
/usr/share/doc/libxml2-2.9.7/html/w3c.png
/usr/share/doc/libxml2-2.9.7/html/writer.xml
/usr/share/doc/libxml2-2.9.7/html/xml.html
/usr/share/doc/libxml2-2.9.7/html/xpath1.c
/usr/share/doc/libxml2-2.9.7/html/xpath1.res
/usr/share/doc/libxml2-2.9.7/html/xpath2.c
/usr/share/doc/libxml2-2.9.7/html/xpath2.res

%files dev
%defattr(-,root,root,-)
/usr/include/libxml2/libxml/DOCBparser.h
/usr/include/libxml2/libxml/HTMLparser.h
/usr/include/libxml2/libxml/HTMLtree.h
/usr/include/libxml2/libxml/SAX.h
/usr/include/libxml2/libxml/SAX2.h
/usr/include/libxml2/libxml/c14n.h
/usr/include/libxml2/libxml/catalog.h
/usr/include/libxml2/libxml/chvalid.h
/usr/include/libxml2/libxml/debugXML.h
/usr/include/libxml2/libxml/dict.h
/usr/include/libxml2/libxml/encoding.h
/usr/include/libxml2/libxml/entities.h
/usr/include/libxml2/libxml/globals.h
/usr/include/libxml2/libxml/hash.h
/usr/include/libxml2/libxml/list.h
/usr/include/libxml2/libxml/nanoftp.h
/usr/include/libxml2/libxml/nanohttp.h
/usr/include/libxml2/libxml/parser.h
/usr/include/libxml2/libxml/parserInternals.h
/usr/include/libxml2/libxml/pattern.h
/usr/include/libxml2/libxml/relaxng.h
/usr/include/libxml2/libxml/schemasInternals.h
/usr/include/libxml2/libxml/schematron.h
/usr/include/libxml2/libxml/threads.h
/usr/include/libxml2/libxml/tree.h
/usr/include/libxml2/libxml/uri.h
/usr/include/libxml2/libxml/valid.h
/usr/include/libxml2/libxml/xinclude.h
/usr/include/libxml2/libxml/xlink.h
/usr/include/libxml2/libxml/xmlIO.h
/usr/include/libxml2/libxml/xmlautomata.h
/usr/include/libxml2/libxml/xmlerror.h
/usr/include/libxml2/libxml/xmlexports.h
/usr/include/libxml2/libxml/xmlmemory.h
/usr/include/libxml2/libxml/xmlmodule.h
/usr/include/libxml2/libxml/xmlreader.h
/usr/include/libxml2/libxml/xmlregexp.h
/usr/include/libxml2/libxml/xmlsave.h
/usr/include/libxml2/libxml/xmlschemas.h
/usr/include/libxml2/libxml/xmlschemastypes.h
/usr/include/libxml2/libxml/xmlstring.h
/usr/include/libxml2/libxml/xmlunicode.h
/usr/include/libxml2/libxml/xmlversion.h
/usr/include/libxml2/libxml/xmlwriter.h
/usr/include/libxml2/libxml/xpath.h
/usr/include/libxml2/libxml/xpathInternals.h
/usr/include/libxml2/libxml/xpointer.h
/usr/lib64/libxml2.so
/usr/lib64/pkgconfig/libxml-2.0.pc
/usr/share/aclocal/*.m4

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
%doc /usr/share/man/man3/*
/usr/share/gtk-doc/html/libxml2/general.html
/usr/share/gtk-doc/html/libxml2/home.png
/usr/share/gtk-doc/html/libxml2/index.html
/usr/share/gtk-doc/html/libxml2/left.png
/usr/share/gtk-doc/html/libxml2/libxml2-DOCBparser.html
/usr/share/gtk-doc/html/libxml2/libxml2-HTMLparser.html
/usr/share/gtk-doc/html/libxml2/libxml2-HTMLtree.html
/usr/share/gtk-doc/html/libxml2/libxml2-SAX.html
/usr/share/gtk-doc/html/libxml2/libxml2-SAX2.html
/usr/share/gtk-doc/html/libxml2/libxml2-c14n.html
/usr/share/gtk-doc/html/libxml2/libxml2-catalog.html
/usr/share/gtk-doc/html/libxml2/libxml2-chvalid.html
/usr/share/gtk-doc/html/libxml2/libxml2-debugXML.html
/usr/share/gtk-doc/html/libxml2/libxml2-dict.html
/usr/share/gtk-doc/html/libxml2/libxml2-encoding.html
/usr/share/gtk-doc/html/libxml2/libxml2-entities.html
/usr/share/gtk-doc/html/libxml2/libxml2-globals.html
/usr/share/gtk-doc/html/libxml2/libxml2-hash.html
/usr/share/gtk-doc/html/libxml2/libxml2-list.html
/usr/share/gtk-doc/html/libxml2/libxml2-nanoftp.html
/usr/share/gtk-doc/html/libxml2/libxml2-nanohttp.html
/usr/share/gtk-doc/html/libxml2/libxml2-parser.html
/usr/share/gtk-doc/html/libxml2/libxml2-parserInternals.html
/usr/share/gtk-doc/html/libxml2/libxml2-pattern.html
/usr/share/gtk-doc/html/libxml2/libxml2-relaxng.html
/usr/share/gtk-doc/html/libxml2/libxml2-schemasInternals.html
/usr/share/gtk-doc/html/libxml2/libxml2-schematron.html
/usr/share/gtk-doc/html/libxml2/libxml2-threads.html
/usr/share/gtk-doc/html/libxml2/libxml2-tree.html
/usr/share/gtk-doc/html/libxml2/libxml2-uri.html
/usr/share/gtk-doc/html/libxml2/libxml2-valid.html
/usr/share/gtk-doc/html/libxml2/libxml2-xinclude.html
/usr/share/gtk-doc/html/libxml2/libxml2-xlink.html
/usr/share/gtk-doc/html/libxml2/libxml2-xmlIO.html
/usr/share/gtk-doc/html/libxml2/libxml2-xmlautomata.html
/usr/share/gtk-doc/html/libxml2/libxml2-xmlerror.html
/usr/share/gtk-doc/html/libxml2/libxml2-xmlexports.html
/usr/share/gtk-doc/html/libxml2/libxml2-xmlmemory.html
/usr/share/gtk-doc/html/libxml2/libxml2-xmlmodule.html
/usr/share/gtk-doc/html/libxml2/libxml2-xmlreader.html
/usr/share/gtk-doc/html/libxml2/libxml2-xmlregexp.html
/usr/share/gtk-doc/html/libxml2/libxml2-xmlsave.html
/usr/share/gtk-doc/html/libxml2/libxml2-xmlschemas.html
/usr/share/gtk-doc/html/libxml2/libxml2-xmlschemastypes.html
/usr/share/gtk-doc/html/libxml2/libxml2-xmlstring.html
/usr/share/gtk-doc/html/libxml2/libxml2-xmlunicode.html
/usr/share/gtk-doc/html/libxml2/libxml2-xmlversion.html
/usr/share/gtk-doc/html/libxml2/libxml2-xmlwriter.html
/usr/share/gtk-doc/html/libxml2/libxml2-xpath.html
/usr/share/gtk-doc/html/libxml2/libxml2-xpathInternals.html
/usr/share/gtk-doc/html/libxml2/libxml2-xpointer.html
/usr/share/gtk-doc/html/libxml2/libxml2.devhelp
/usr/share/gtk-doc/html/libxml2/right.png
/usr/share/gtk-doc/html/libxml2/style.css
/usr/share/gtk-doc/html/libxml2/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/libxml2.so.2
/usr/lib64/libxml2.so.2.9.7
